server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/file-service
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
app:
  file:
    storage-dir: ${user.home}/Documents/uploads
    download-prefix: http://localhost:8888/api/v1/file/media/download/
